/* Populate tables */
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(1,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(2,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(3,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(4,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(5,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(6,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(7,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(8,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(9,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(10,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(11,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(12,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(13,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(14,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(15,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(16,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(17,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(18,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(19,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(20,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(21,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(22,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(23,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(24,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(25,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(26,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(27,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(28,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(29,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(30,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(31,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(32,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(33,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(34,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(35,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(36,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(37,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(38,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(39,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(40,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(41,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(42,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(43,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28', ' '); 
INSERT INTO clientes(id, nombre, apellido, email, create_at, foto)VALUES(44,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28', ' '); 