/* Populate tables */
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(1,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(2,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(3,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(4,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(5,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(6,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(7,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(8,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(9,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(10,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(11,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(12,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(13,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(14,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(15,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(16,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(17,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(18,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(19,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(20,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(21,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(22,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(23,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(24,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(25,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(26,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(27,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(28,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(29,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(30,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(31,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(32,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(33,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(34,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(35,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(36,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(37,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(38,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(39,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(40,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(41,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(42,'Rosario', 'Sanchez', 'charo@mail.com', '2011-10-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(43,'Mauricio', 'Sanchez', 'maurisan42@mail.com','2018-08-28'); 
INSERT INTO clientes(id, nombre, apellido, email, create_at)VALUES(44,'ALan', 'Cabot', 'cabort@mail.com', '2020-08-28'); 